export enum TipoItemEnum {
  PRODUCTO = 'PRODUCTO',
  PAQUETE = 'PAQUETE',
}

export enum TipoOperacionEnum {
  VENTA = 'VENTA',
  CAMBIO = 'CAMBIO',
  AJUSTE = 'AJUSTE',
}

export enum EstadoReservaEnum {
  ACTIVA = 'ACTIVA',
  CONSOLIDADA = 'CONSOLIDADA',
  LIBERADA = 'LIBERADA',
  EXPIRADA = 'EXPIRADA',
}

export enum TipoMovimientoEnum {
  VENTA_SALIDA = 'VENTA_SALIDA',
  CAMBIO_SALIDA = 'CAMBIO_SALIDA',
  CAMBIO_ENTRADA = 'CAMBIO_ENTRADA',
  AJUSTE_OPERATIVO = 'AJUSTE_OPERATIVO',
  AJUSTE_CONTABLE = 'AJUSTE_CONTABLE',
  RESERVA = 'RESERVA',
  LIBERACION = 'LIBERACION',
  ABANDONO_ENTRADA = 'ABANDONO_ENTRADA',
  ABANDONO_SALIDA = 'ABANDONO_SALIDA',
}

export enum TipoActorEnum {
  EMPLEADO = 'EMPLEADO',
  CLIENTE = 'CLIENTE',
  SISTEMA = 'SISTEMA',
}
